[tool.black]
line-length = 88  # Настройки black
exclude = '''
/(
  | venv
  | migrations
)/
'''

[tool.isort]
profile = "black"
skip = ["venv", "migrations", "__pycache__", ".git", ".pytest_cache"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"